# install project dependencies and run tests

name: test project

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies with pipenv
      run: |
        python -m pip install --upgrade pip
        pip install --user pipenv
        pipenv install
        pipenv shell
    - name: Test with pytest
      run: |
        pytest
